apiVersion: v2
name: kas
description: k8s agent server
version: 0.0.0
appVersion: "0.0.0"
dependencies:
  - name: redis
    version: 24.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: ingress-nginx
    alias: nginx
    version: 4.14.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: nginx.enabled
  - name: cert-manager
    version: v1.19.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
