apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kas.fullname" . }}
  labels:
    {{- include "kas.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.kas_dns | quote }}
      http:
        paths:
          - path: /ext/kas
            pathType: Prefix
            backend:
              service:
                name: {{ include "kas.serviceName" . }}
                port:
                  number: {{ .Values.agent.proxy.port }}
  {{ if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.kas_dns | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{ end }}
